### ISSUE TITLE
Unsupported image type exceptions and hang encountered

### ISSUE THREAD

**Issue by rrussell39** [serenity-bdd/serenity-core#145]
I am seeing the following output recently in my logging:

00:21:44 Exception in thread "pool-1-thread-3" net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@110bd1ea
00:21:44 	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:179)
00:21:44 	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:22)
00:21:44 	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:113)
00:21:44 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
00:21:44 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
00:21:44 	at java.lang.Thread.run(Thread.java:745)
00:21:44 Caused by: java.io.IOException: Unsupported image type
00:21:44 	at net.thucydides.core.images.SimpleImageInfo.processStream(SimpleImageInfo.java:63)
00:21:44 	at net.thucydides.core.images.SimpleImageInfo.<init>(SimpleImageInfo.java:44)
00:21:44 	at net.thucydides.core.images.ResizableImage.<init>(ResizableImage.java:33)
00:21:44 	at net.thucydides.core.images.ResizableImage.loadFrom(ResizableImage.java:37)
00:21:44 	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.maxHeightOf(HtmlAcceptanceTestReporter.java:233)
00:21:44 	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.maxScreenshotHeightIn(HtmlAcceptanceTestReporter.java:226)
00:21:44 	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.expandScreenshots(HtmlAcceptanceTestReporter.java:193)
00:21:44 	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:178)
00:21:44 	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:88)
00:21:44 	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:177)
00:21:44 	... 5 more

This appears to happen after all the tests have run and the report is being generated.  I've recently started using Serenity 1.1.14 though I'm not 100% convinced that correlates.   What may be a contributing factor are newly added tests which loop through about 20 different locales verifying links for each locale.  
My screen capture setting is the default (before and after).
We are using Java 1.7 + Junit + Serenity 1.1.14 + Saucelabs.  This particular failure happened on Win8.1 + IE 11. 

Then, the build runs endlessly:
00:21:45 2015-10-10T00:21:22.634-0700 ... [pool-1-thread-4] INFO  net.thucydides.core.reports.ReportService$1.run:115 Processing test outcome Verify and save analytics account:invalidUsername done
02:16:57 Build timed out (after 240 minutes). Marking the build as aborted.
(Notice that Jenkins aborts the build after 240 mins)  The last thing that was executed that seems to hang is: net.thucydides.core.reports.ReportService

**Comment by wakaleo** [comment]
I've never seen anything like this before. Is there another stack dump
associated with this? This one doesn't say where the IOException happened.

On 13 October 2015 at 04:43, rrussell39 <notifications@github.com> wrote:

> I am seeing the following output recently in my logging:
>
> 00:21:44 Exception in thread "pool-1-thread-3"
> net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate
> reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@
> 110bd1e
> <https://github.com/net.thucydides.core.reports.html.HtmlAcceptanceTestReporter/serenity-core/commit/110bd1ea>
> 00:21:44 at
> net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:179)
> 00:21:44 at
> net.thucydides.core.reports.ReportService.access$100(ReportService.java:22)
> 00:21:44 at
> net.thucydides.core.reports.ReportService$1.run(ReportService.java:113)
> 00:21:44 at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 00:21:44 at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 00:21:44 at java.lang.Thread.run(Thread.java:745)
> 00:21:44 Caused by: java.io.IOException: Unsupported image type
>
> This appears to happen after all the tests have run and the report is
> being generated. I've recently started using Serenity 1.1.14 though I'm not
> 100% convinced that correlates. What may be a contributing factor are newly
> added tests which loop through about 20 different locales verifying links
> for each locale.
>
> My screen capture setting is the default (before and after).
> We are using Java 1.7 + Junit + Serenity 1.1.14 + Saucelabs. This
> particular failure happened on Win8.1 + IE 11.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/145>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by rrussell39** [comment]
Ok - I added the stack dump lines (to my original post above) preceding the exception line: 00:21:44 Caused by: java.io.IOException: Unsupported image type.  Let me know if there is anything else I can provide.  I actually repro'd this locally on my Mac laptop but it is intermittent for sure.

**Comment by verhagen** [comment]
_Just trying to get more background information_

- Does this happen for all the tests cases.  
_Meaning_ If you run just a few test cases, say 5 or 10, does it happen then as well ? Or does it just happen for some specific test cases ?
- Does it happen on all OSes and Browser combinations or only on Windows 8.1 with IE11 ?
- Can you check if it happens with a previous version of Serenity (like v1.1.3 or v1.1.2), as well ?

**Comment by rrussell39** [comment]
Q: Does this happen for all the tests cases. Meaning If you run just a few test cases, say 5 or 10, does it happen then as well ? Or does it just happen for some specific test cases ?
A: This is happening pretty consistently for a set of tests that are tagged as 'acceptance' for one of our Apps.  There are 63 such tests.  I tried running a small subset (3) of those tests locally (using Saucelabs Win8.1/InternetExplorer11) and it did not reproduce.

Q:  Does it happen on all OSes and Browser combinations or only on Windows 8.1 with IE11 ?
A: I'm only seeing this with Win8.1/IE11 so far.

Q: Can you check if it happens with a previous version of Serenity (like v1.1.3 or v1.1.2), as well ?
A: I will report back on this.

**Comment by rrussell39** [comment]
Quick update - I'm looking back at my build history for the failing tests and the last time it worked was when I used Serenity 1.0.59 so I think it's highly likely that when I upgraded to 1.1.14, something broke in the reporting process.

**Comment by verhagen** [comment]
Ok, thx for the additional details.

**Comment by rrussell39** [comment]
Yes - this does happen with Serenity 1.1.3.  Took a long time to validate that due to the fact that I have to run all the acceptance tests to reproduce it.  Here is some of that log:

2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-8] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:49 Resizing image target/site/thucydides/acbed48f2fc73464300632cebeba32cb_NONE.png to target/site/thucydides/scaled_acbed48f2fc73464300632cebeba32cb_NONE.png
2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-10] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:51 Resized screenshot existstrue
2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-8] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:50 Screenshot existstrue
2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-10] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:49 Resizing image target/site/thucydides/f74d8dabb1792d0ee53cb301ab080476_NONE.png to target/site/thucydides/scaled_f74d8dabb1792d0ee53cb301ab080476_NONE.png
Exception in thread "pool-2-thread-9" net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@4eb85fa9
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:183)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:23)2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-8] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:51 Resized screenshot existstrue

	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-10] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:50 Screenshot existstrue

	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unsupported image type
2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-11] INFO  net.thucydides.core.reports.ReportService$1.run:113 Processing test outcome Click go url links:allGoUrlsExistAndFooterCookieLangMatchForPolish
	at net.thucydides.core.images.SimpleImageInfo.processStream(SimpleImageInfo.java:63)
	at net.thucydides.core.images.SimpleImageInfo.<init>(SimpleImageInfo.java:44)
	at net.thucydides.core.images.ResizableImage.<init>(ResizableImage.java:33)
	at net.thucydides.core.images.ResizableImage.loadFrom(ResizableImage.java:37)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.maxHeightOf(HtmlAcceptanceTestReporter.java:233)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.maxScreenshotHeightIn(HtmlAcceptanceTestReporter.java:226)2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-8] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:49 Resizing image target/site/thucydides/acbed48f2fc73464300632cebeba32cb_NONE.png to target/site/thucydides/scaled_acbed48f2fc73464300632cebeba32cb_NONE.png

	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.expandScreenshots(HtmlAcceptanceTestReporter.java:193)2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-10] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:51 Resized screenshot existstrue

	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:178)2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-11] INFO  net.thucydides.core.reports.ReportService.generateReportFor:179 net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@4eb85fa9: Generating report for test outcome: Click go url links:allGoUrlsExistAndFooterCookieLangMatchForPolish

	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:88)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:181)
	... 5 more
2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-8] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:50 Screenshot existstrue
2015-10-13T17:23:12.878-0700 srv="portal-automation-welcome" [pool-2-thread-10] INFO  net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight:49 Resizing image target/site/thucydides/f74d8dabb1792d0ee53cb301ab080476_NONE.png to target/site/thucydides/scaled_f74d8dabb1792d0ee53cb301ab080476_NONE.png

And things are now hung and here are the last few lines showing:
2015-10-13T17:23:12.902-0700 srv="portal-automation-welcome" [pool-2-thread-4] INFO  net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor:98 GENERATING HTML REPORT FOR Click go url links:allGoUrlsExistAndFooterCookieLangMatchForEnUKAsPreferredLang => 16972a09a95c144228b6f444aa7ec0e96bbfa6d0fcce20f511a4373e3b84645c.html
2015-10-13T17:23:12.909-0700 srv="portal-automation-welcome" [pool-2-thread-10] INFO  net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor:98 GENERATING HTML REPORT FOR Click go url links:multipleLangaugeFallbackIfPreferredLangNotSupported => 16b2d6789f0d20bb762f47c20535abaad80742390d223445d55e4c7443924820.html
2015-10-13T17:23:12.913-0700 srv="portal-automation-welcome" [pool-2-thread-4] INFO  net.thucydides.core.reports.ReportService$1.run:116 Processing test outcome Click go url links:allGoUrlsExistAndFooterCookieLangMatchForEnUKAsPreferredLang done
2015-10-13T17:23:12.922-0700 srv="portal-automation-welcome" [pool-2-thread-10] INFO  net.thucydides.core.reports.ReportService$1.run:116 Processing test outcome Click go url links:multipleLangaugeFallbackIfPreferredLangNotSupported done
2015-10-13T17:23:12.942-0700 srv="portal-automation-welcome" [pool-2-thread-8] INFO  net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor:98 GENERATING HTML REPORT FOR Click go url links:allGoUrlsExistAndFooterCookieLangMatchForKorean => c0f680a3d92ed5dfef7b69dbca9b22b731f349afdd31f3e9bba3e4558babf7e0.html
2015-10-13T17:23:12.952-0700 srv="portal-automation-welcome" [pool-2-thread-8] INFO  net.thucydides.core.reports.ReportService$1.run:116 Processing test outcome Click go url links:allGoUrlsExistAndFooterCookieLangMatchForKorean done

**Comment by wakaleo** [comment]
Nothing's changed in that code, so it might be due to a selenium change. In any case I've rewritten the screenshot logic to make it a but more flexible with different formats.

**Comment by rrussell39** [comment]
Serenity 1.1.3 (which shows the problem above) uses Selenium 2.46.0.  The last good version (that worked for us on Win8.1/IE11) of Serenity that I used (1.0.59) used Selenium 2.46.0 as well.  So I'm lead to believe that Selenium changes are not the issue but I could be wrong in my analysis.

I do see these most recent commits in the ReportService class (which is indicated in the error output log):
4b5298def11a9989dc5e7a9c5922a24aa71112bd
de2d4287aab991f99a6553943418d1da15f5b3af (this one seems to be tied to 1.1.8 but not sure)
Is it possible to double check the code in this area?  
I am getting this every time I run a certain set of tests.  Unfortunately, it is a long list so it's tough to narrow down to a small, reproducible subset.
I will keep working on this but any help here would be much appreciated.

Thanks,
Rob

**Comment by rrussell39** [comment]
By the way - you mentioned you've rewritten the screenshot logic.  Can you confirm which version I should get to experiment with?

**Comment by mikezx6r** [comment]
I also see this in RHEL 6 using PhantomJS, and Serenity version 1.1.13. Doesn't always happen, but I've definitely seen it in most runs of the suite. Haven't discovered the pattern, nor the affect on the reports (if any).

1.1.15 has the new screenshot functionality, BUT it is not compatible with JDK7. If you're running 8, you should be good, but I'm stuck running 7. I've submitted a pull request to fix JDK7 compatibility, but CI didn't pass because of a timeout, and I don't have to a way to trigger it again.

**Comment by verhagen** [comment]
@mikezx6r __Workaround:__ You can just commit a small modification (add a space or so) and push it on the branch. It will trigger a new build for the pull request.

**Comment by rrussell39** [comment]
Ok - I found out what the issue is. 

I have a test which changes the locale of the portal I'm testing to any of several locales then verifies the links on the page.  I have a step which clicks on a language in a dropdown box.  If you run this test on win8.1/IE11 it will hang during the report generation phase with "java.io.IOException: Unsupported image type".  If you analyze the site/thucydides directory, you'll see a zero byte png file among other valid png files.
Figuring that the screenshot was taken before the page rerendered after changing the language, I added a wait of 1 second after the dropdown language is clicked in the step method (important).  Sure enough, problem goes away.

So I'm guessing that on this configuration (win/ie) that the page load takes a little longer than other browser+OS configs OR the notification process between the step handler and the screen shot manager is out of sync.
Either way, I think at least one issue to fix is to ensure that the reporting engine (ReportService?) doesn't choke on a zero byte png file if in fact that is the root issue.
I tested this with Firefox 38 and Win8.1 and it did not happen.  I can only repro on Win8.1 + IE 11.

I went back and tested several versions of Serenity and this issue started in tag=v1.1.2

**Comment by rrussell39** [comment]
Just noticed this PR <a href="https://github.com/serenity-bdd/serenity-core/pull/148/files">[serenity-core] fix loop when parameter is null in ddt tests (#148)</a> which fixes a (separate?) hang in ReportService.  Wonder if they are related?

**Comment by rrussell39** [comment]
@wakaleo It is turning out that my workaround is not always working to avoid this problem.  As a result, my failed build times out and is eventually aborted by Jenkins.  At this point, this is a deal breaker and I'm considering rolling back Serenity to a version earlier than 1.1.2.  Can you tell me what, if any, priority this has?  I'd work on it myself but I can't even compile the code on my java 1.7 system due to a separate <a href="https://github.com/serenity-bdd/serenity-core/issues/144">build issue</a>.  Also, if I choose to get a newer version of Serenity, is it mandatory to have it running on Java 8?  I'm stuck with 7 for now.

**Comment by mikezx6r** [comment]
JDK8 is not mandatory, but sometimes a JDK8 convention will slip in. I've corrected a couple recently as I am also stuck on JDK7. The JDK7 compatible version is currently 1.1.17-rc.1

The entire screenshot processor has been rewritten, and there was a recent commit where there was a threading issue with the screen reporter. The threading commit hasn't been put into a release yet.

**Comment by wakaleo** [comment]
Have you tried with 1.1.7-rc.1?

**Comment by rrussell39** [comment]
I will give it a go and report back.  Thanks!

**Comment by rrussell39** [comment]
So far so good with some tests.  I will report back tomorrow with further, more complete results.  One thing I noticed however, is that the Serenity version tag in the reports still shows 1.1.14.  That is very confusing.
![screen shot 2015-10-21 at 5 24 47 pm](https://cloud.githubusercontent.com/assets/8116184/10653882/bf5882c0-7818-11e5-9850-5a85c27ee503.png)

**Comment by rrussell39** [comment]
Ok - the one test app I had that was consistently having the problem is no longer displaying the issue when I updated to 1.1.17-rc.1.  Thanks!  I'm going to deploy across all my test apps and monitor going forward.  I'll close this out after a couple days when each test has run a couple times.

**Comment by rrussell39** [comment]
Update - things have gotten worse.  BUT the scenario is a little complicated.  Here is the recent log output:
09:11:50 Exception in thread "pool-2-thread-1" net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@5a965620
09:11:50 	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:179)
09:11:50 	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:22)
09:11:50 	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:113)
09:11:50 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09:11:50 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
09:11:50 	at java.lang.Thread.run(Thread.java:745)
09:11:50 Caused by: java.nio.file.FileSystemException: target/site/thucydides/e357add6d025a16325558f30e9e38ec300e5598177b8c59beae99c1b4031a1cc.html: <b>Too many open files</b>

Here is the complicated part.  We have a parent pom file project which our client test app's include.  We also have the base shared library we develop that all of our client test apps utilize.  We used to be able to specify one version for serenity-core, serenity-junit, and serenity maven plugin.  However, when I updated to 1.1.17-rc.1 I could no longer do that because the serenity maven plugin 1.1.17-rc.1 could not be found.  1.1.14 could be found so I used that version for the serenity maven plugin.  So with those changes, things have gotten worse, or perhaps different, as I don't see the original "Unsupported image type" problem, I  now see, "Too many open files" and things go badly after that.

In my test above where I reported that things got better, (see above "So far so good with some tests.") I only had our shared automation library updated to 1.1.17-rc.1 and all other serenity components in our parent pom project at 1.1.14.  I guess I can try to revert to that but it seems like things are disjoint now between 1.1.17-rc.1 and 1.1.14.

Thanks for any clarity around this.

**Comment by wakaleo** [comment]
You will need to add a dependency on the RC version to your maven plugin
for this to work. Could you try with the latest RC (1.1.17-rc.3)?

On 23 October 2015 at 19:02, rrussell39 <notifications@github.com> wrote:

> Update - things have gotten worse. BUT the scenario is a little
> complicated. Here is the recent log output:
> 09:11:50 Exception in thread "pool-2-thread-1"
> net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate
> reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@
> 5a96562
> <https://github.com/net.thucydides.core.reports.html.HtmlAcceptanceTestReporter/serenity-core/commit/5a965620>
> 09:11:50 at
> net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:179)
> 09:11:50 at
> net.thucydides.core.reports.ReportService.access$100(ReportService.java:22)
> 09:11:50 at
> net.thucydides.core.reports.ReportService$1.run(ReportService.java:113)
> 09:11:50 at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 09:11:50 at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 09:11:50 at java.lang.Thread.run(Thread.java:745)
> 09:11:50 Caused by: java.nio.file.FileSystemException:
> target/site/thucydides/e357add6d025a16325558f30e9e38ec300e5598177b8c59beae99c1b4031a1cc.html:
> *Too many open files*
>
> Here is the complicated part. We have a parent pom file project which our
> client test app's include. We also have the base shared library we develop
> that all of our client test apps utilize. We used to be able to specify one
> version for serenity-core, serenity-junit, and serenity maven plugin.
> However, when I updated to 1.1.17-rc.1 I could no longer do that because
> the serenity maven plugin 1.1.17-rc.1 could not be found. 1.1.14 could be
> found so I used that version for the serenity maven plugin. So with those
> changes, things have gotten worse, or perhaps different, as I don't see the
> original "Unsupported image type" problem, I now see, "Too many open files"
> and things go badly after that.
>
> In my test above where I reported that things got better, (see above "So
> far so good with some tests.") I only had our shared automation library
> updated to 1.1.17-rc.1 and all other serenity components in our parent pom
> project at 1.1.14. I guess I can try to revert to that but it seems like
> things are disjoint now between 1.1.17-rc.1 and 1.1.14.
>
> Thanks for any clarity around this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/145#issuecomment-150648769>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by rrussell39** [comment]
Ok - let me try that.

**Comment by rrussell39** [comment]
> mvn clean -U install

[ERROR] Plugin net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.1.17-rc.3 or one of its dependencies could not be resolved: Failure to find net.serenity-bdd.maven.plugins:serenity-maven-plugin:jar:1.1.17-rc.3 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by wakaleo** [comment]
You need to add the serenity-core dependency on 1.1.17-rc.3, not use the
maven release - the maven release can't be done until the core version is
validated,

On 23 October 2015 at 19:20, rrussell39 <notifications@github.com> wrote:

> mvn clean -U install
>
> [ERROR] Plugin
> net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.1.17-rc.3 or one of
> its dependencies could not be resolved: Failure to find
> net.serenity-bdd.maven.plugins:serenity-maven-plugin:jar:1.1.17-rc.3 in
> http://repo.maven.apache.org/maven2 was cached in the local repository,
> resolution will not be reattempted until the update interval of central has
> elapsed or updates are forced -> [Help 1]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/145#issuecomment-150653488>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by rrussell39** [comment]
Ok - how do I not use the maven release?

**Comment by mikezx6r** [comment]
@rrussell39 The issue is the maven-plugin is bringing in serenity-core 1.1.14. The easiest way to override that is to define serenity-core 1.1.17-rc.3 in dependencyManagement of your pom. 

Then the maven-plugin 1.1.14 will retrieve serenity-core 1.1.17-rc.3 instead of 1.1.14.

I've successfully execute my FT suite using this approach.

HTH

**Comment by rrussell39** [comment]
Thanks @mikezx6r and @wakaleo .  I'm using Eclipse which has "Effective Pom" tab which shows how things ultimately resolve.  Here is what I end up with (removing unrelated items):

  <dependencyManagement>
    <dependencies>
...
      <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-core</artifactId>
        <version>1.1.17-rc.3</version>
      </dependency>
      <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-api</artifactId>
        <version>2.48.2</version>
      </dependency>
      <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-junit</artifactId>
        <version>1.1.17-rc.3</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
      </dependency>
      <dependency>
        <groupId>com.google</groupId>
        <artifactId>chromedriver</artifactId>
        <version>2.10</version>
        <type>zip</type>
      </dependency>
  </dependencyManagement>

This compiles ok.  I can give this a shot and report back later if it looks correct.

**Comment by mikezx6r** [comment]
Does the effective pom show the dependencies for the serenity-maven-plugin? That's the one that's giving you trouble when it attempts to execute and aggregate the reports.

If you don't force maven, it will bring in the older version of core when it resolves the dependencies of serenity-maven-plugin.

If it looks like serenity-maven-plugin is now depending on 1.1.17-rc.3, you'll be good to go.

**Comment by rrussell39** [comment]
Sorry - I'm not sure I'm getting this dialed in correctly.  My last set of tests still show the hang problem.  I'm reverting to 1.0.59 to stabilize things.  

Would it be possible to post a sample pom file?  Perhaps use the Serenity Smoke Tests project as a template?

And I have one very basic question - does the serenity maven plugin assets for 1.1.17-rc.3 exist and where are they if so - bintray or maven2 or ???.  I don't see them anywhere but I'm not sure I'm suppose to since they are not actually released yet.

**Comment by mikezx6r** [comment]
The serenity-maven-plugin 1.1.17-rc.3 has not been released, partially because no changes have occurred internally.

The problem is that the version you're using is bringing in an old serenity dependency, but you're tests were run with the new version. 

Plugin execution and dependency resolution is done independently of the test run, hence the compile dependency you defined for Serenity of 1.1.17-rc.3 has NO EFFECT on the dependency being used when the maven plugin runs.

I'll gather together the sample pom as you suggest, and post it shortly.

**Comment by mikezx6r** [comment]
- Update serenity.version = 1.1.17.rc-3
- Add DependencyManagement section

This is working for my tests, so if this update doesn't work for you, then perhaps something else is different about your environment. Let me know

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>net.serenitybdd.demos.todos</groupId>
    <artifactId>todo-demo</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Sample Serenity project using Cucumber and WebDriver</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.17-rc.3</serenity.version>
        <serenity.maven.version>1.1.14</serenity.maven.version>
        <webdriver.driver>firefox</webdriver.driver>
        <parallel.tests>4</parallel.tests>
    </properties>

    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray</name>
            <url>http://jcenter.bintray.com</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray-plugins</name>
            <url>http://jcenter.bintray.com</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-core</artifactId>
                <version>${serenity.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-journey</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>browse-the-web</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/features/**/*.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <parallel>classes</parallel>
                    <threadCount>${parallel.tests}</threadCount>
                    <forkCount>${parallel.tests}</forkCount>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenitybdd.demos.todos</groupId>
                        <artifactId>todo-demo</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by rrussell39** [comment]
Great - thanks for the quick turn-around on this.  Let me try it soon and get back to you!

**Comment by rrussell39** [comment]
Sorry, I have not had a chance to revisit this but I'm just looking a little more closely now at the pom you posted.  The versions of serenity (1.1.17-rc.3) and serenity maven plugin (1.1.14) were identical to that which I tried.  
I guess this leads me to believe there is still something unique about my tests and/or environment that are causing this issue.
The thread is so long now I think the most important items may be lost or at least hard to find.  To reiterate: Win8.1/IE11: I had a reproducible scenario whereby when I changed the language for the portal I'm testing I would see the problem.  (I could see a 0-byte jpg file in the screenshots dir).  When I added a one second delay after changing the language (in the same step that changes the lang) the problem went away.

**Comment by rrussell39** [comment]
Revisiting this.  Any new movements?  I'm going to try the latest stable version (1.21 ?) to see what happens.

**Comment by YamStranger** [comment]
Hello @rrussell39. 

It will be better, if you try 1.1.22-rc.10. There was some updates for image processing. 

Thanks

**Comment by rrussell39** [comment]
@YamStranger Ok - thanks.  I will try that.

**Comment by rrussell39** [comment]
@YamStranger I'm still seeing an unspecified hang of some sort using 1.1.22-rc.10 and 1.1.21 of serenity.maven.plugin.version.  It happens on different browser/os configs.  Happens after most of 88-90 tests are completed.  In one case, the apparent hang happens during the after-tests reporting process.  In another, a test has just completed and then a hang seems to be encountered.

**Comment by kamalshingala** [comment]
Hi @YamStranger, I am facing issue with reports being generated very slow (While running a test with for e.g. 10 test scenarios, report generation service aggregates and compiles reports starting from scenario 1 every time i.e scenario1, report generated for scenario 1, scenario 2 execution, report generated for scenario 1 and 2 and so on.. and I am using serenity version 1.1.21. I tried using latest version of serenity 1.1.29-rc.2 as you suggested and it looks to be generating report quickly, however it doesnt show the step started and step done in the output logs.

My pom.xml looks like below -

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>uitest</groupId>
    <artifactId>webtest</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Sample Serenity project using Cucumber and WebDriver</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.21</serenity.version>
        <serenity.cucumber.version>1.1.2</serenity.cucumber.version>
        <webdriver.driver>chrome</webdriver.driver>
    </properties>



    <reporting>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>findbugs-maven-plugin</artifactId>
                <version>3.0.2</version>
                <configuration>
                    <xmlOutput>true</xmlOutput>
                    <xmlOutputDirectory>target/site</xmlOutputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </reporting>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20151123</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/unittest/*.java</include>
                    </includes>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/binding/*.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by YamStranger** [comment]
Hello @kamalshingala 
Please open different issue for you quetion/bug. It seems that is something different from "Unsupported image type exceptions and hang encountered #145"

Thanks!

**Comment by kamalshingala** [comment]
Hi @YamStranger, I have created separate issue #382 for the issue I am facing.

**Comment by wakaleo** [comment]
Hi @rrussell39 and @kamalshingala, are you still seeing this issue in 1.1.31?

**Comment by rrussell39** [comment]
I have been using 1.1.29-rc.1 for some time now and things seem fine with regards to this issue.  We can close this out.
