### ISSUE TITLE
Problems with taking full page screenshots, documented with demo project

### ISSUE THREAD

**Issue by SchnuckySchuster** [serenity-bdd/serenity-core#2554]
How to reproduce:
- git clone https://github.com/SchnuckySchuster/Serenity-BDD-Screenplay-Example-with-Cucumber.git
- Change the settings as described below
- mvn clean verify
- Look in to the test protocol and check the size of the page screen shot 

# Serenity-BDD-Screenplay-Example-with-Cucumber

This project exists to demonstrate specific aspects of Serenity.

## Taking screenshots

After updating to a newer Serenity version I could no longer take full page screenshots.
This is the demonstrator for my calamity.

## Starting point

I have a nice test suite where I'm using Serenity 2.4.4.

I use following configuration in order to take full screen screenshots and it works fine.

```    
    serenity.full.page.screenshot.strategy = true
```

Now I want to update to the latest version and there the problems start.

### Old WebDriver screenshot config

With the newest Serenity Version this

```    
    serenity.full.page.screenshot.strategy = true
```

does not take full page screen shots any longer.

### Shuterbug 0.9.5

With the settings given in the manual
```    
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-shutterbug</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        
        serernity.screenshooter = shutterbug

        shutterbug {
            #scrollstrategy = VIEWPORT_ONLY (or) WHOLE_PAGE (or) WHOLE_PAGE_SCROLL_AND_STITCH
            scrollstrategy = WHOLE_PAGE
            betweenScrollTimeout = 100
            useDevicePixelRatio = true
        }
```    
I see full page screenshots, but

- The settings WHOLE_PAGE (or) WHOLE_PAGE_SCROLL_AND_STITCH both behave the same
- It takes ages to take the screenshots, meaning it is possible but not feasible to take full page screenshots with shutterbug 0.9.5

### Shuterbug 1.5

With the settings given in the manual
```    
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-shutterbug1x</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        
        serernity.screenshooter = shutterbug1x

        shutterbug {
            #capturestrategy = VIEWPORT (or) FULL (or) FULL_SCROLL (or) VERTICAL_SCROLL (or) HORIZONTAL_SCROLL
            capturestrategy = FULL_SCROLL
            betweenScrollTimeout = 100
            useDevicePixelRatio = true
        }
```    
I'm not able to create full page screenshots. It looks like the parameter 'capturestrategy' takes no effect.

**Comment by wakaleo** [comment]
Could you take a look at the code and see if you can propose any changes?

**Comment by SchnuckySchuster** [comment]
Well, I'm a pretty good Java programmer when it comms to test automation,  but by skill level is not sufficient for real live Java programming.

I had raised this bug some time ago and I saied I will create a project to demonstrate the problem when I got some time.

This is not much of a pain for me as long as I don't ever upgrade the version.

**Comment by pogodins** [comment]
@wakaleo, @SchnuckySchuster I'm currently looking into this issue and found why capturestrategy is being ignored. Still need to test some scenarios. When it's fixed, I'll link this issue.

**Comment by SchnuckySchuster** [comment]
👍

**Comment by pogodins** [comment]
@SchnuckySchuster the issue is fixed in #2628.
Until it's released you can use deprecated property `serenity.full.page.screenshot.strategy = true`.

**Comment by SchnuckySchuster** [comment]
Hi Serghei,

thanks a lot.


Gerhard

**Comment by SchnuckySchuster** [comment]
Hi @pogodins, hi @wakaleo, 

I’ve found some time to checkout the bugfix.
I’ve updated my demo project to serenity-core 3.1.10. (https://github.com/SchnuckySchuster/Serenity-BDD-Screenplay-Example-with-Cucumber)

I’m still not able to make this version print the entire page.
It might be that I’m using an improper configuration. I tried several though.

Can you please have a look and maybe send me the correct configuration file, or create a fork and a pullrequest? 

I’d really like to update to the new verson as the reports look so much cooler.

Gerhard

**Comment by pogodins** [comment]
Hi @SchnuckySchuster,
The fix I did will be available in version 3.1.11.
Until that moment you can use workaround I proposed above.
I'm using 3.1.10 in my project with the workaround and full screenshots are coming.

**Comment by SchnuckySchuster** [comment]
Well, reading seems to be an art that I’m not very good at.
Thanks for the hint.

**Comment by SchnuckySchuster** [comment]
Here an update:
I used the configuration below but the screenshot was not a full screen.
I will wait for 3.1.11. In case this bug is not fixed there I think I will still upgrade because the result looks so much nicer than in the version I'm using.

serenity {
    project.name = "Example project for John"
    test.root = "net.demos.todos.features"
    tag.failures = true
    linked.tags = issue
    restart.browser.for.each = scenario
    full.page.screenshot.strategy = true
    take.screenshots = BEFORE_AND_AFTER_EACH_STEP
    #screenshooter = shutterbug1x
}

# shutterbug {
# 	#capturestrategy = VIEWPORT (or) FULL (or) FULL_SCROLL (or) VERTICAL_SCROLL (or) HORIZONTAL_SCROLL
#     capturestrategy = FULL
#     #scrollstrategy = VIEWPORT_ONLY (or) WHOLE_PAGE (or) WHOLE_PAGE_SCROLL_AND_STITCH
#     scrollstrategy = WHOLE_PAGE
#     betweenScrollTimeout = 10
#     useDevicePixelRatio = true
# }

**Comment by pogodins** [comment]
@SchnuckySchuster Indeed, it's important to read carefully. Please uncomment the following to get it qorking with 3.1.10 #screenshooter = shutterbug1x.

**Comment by SchnuckySchuster** [comment]
I did not do that because the application did crash after taking the first screenshot with this setting uncommented.

The reason why this happened was that I forgot to uncomment the respective section in my pom file

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-shutterbug1x</artifactId>
            <version>${serenity.version}</version>
        </dependency>

Instead I used
       <dependency>
           <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-shutterbug</artifactId>
            <version>${serenity.version}</version>
        </dependency>

Now it works.
